### ISSUE TITLE
Documentation on common CSS

### ISSUE THREAD

**Issue by plug-n-play** [vercel/next-site#343]
While https://nextjs.org/learn/basics/styling-components contains excellent explanation on Component-Styling, we should ideally explain following as well:
1. How to create common styles which are shared amongst different components
2. How to add third party styling libraries

**Comment by lidoravitan** [comment]
@timneutkens is still relevant? i'd like to help here

**Comment by amlidajames** [comment]
relevant?

**Comment by timneutkens** [comment]
This has been solved after the rewrite of /learn
