### ISSUE TITLE
No short description about what NextJS is

### ISSUE THREAD

**Issue by baaym** [vercel/next-site#735]
Hi all,

I was passing by your website out of curiosity after I saw a reference to the `next` npm module somewhere. I was looking for a simple one-line description that could give me a bit of context about NextJS, but couldn't find it on any of the pages, or event the documentation site. After a bit of digging I found "_Production grade React applications that scale. The world’s leading companies use Next.js by Vercel to build static and dynamic websites and web applications._" in the `description` meta field of the homepage.

This snippet actually gave me the context I needed, and perhaps something like this should find its way to a bit more prominent place on the homepage?

Regards,

**Comment by lfades** [comment]
Closing as our website now provides a clear description in the landing page about what Next.js is:

![image](https://user-images.githubusercontent.com/4278345/92409921-e8249c80-f107-11ea-9cf3-5f7b4b6b382a.png)

Let me know if you still think it's lacking something 👍
