### ISSUE TITLE
Cannot generate  Next conf ticket image

### ISSUE THREAD

**Issue by balazsorban44** [vercel/next-site#788]
I have registered, got the verification e-mail, clicked "Generate with GitHub", gave permission, got redirected back, but when I go to the following URL, I get a 404:

https://nextjs.org/conf/tickets/balazsorban44

**Update**: I ran registering again in incognito mode, than it worked! I use Chrome Canary and  Chrome stable on my phone. I started the registering from Canary, but I was redirected to the GitHub consent screen in stable, got redirected back into Canary. I guess this messed things up. In incognito I was able to stay in the same browser under the whole process.

**Comment by chibicode** [comment]
Hi @balazsorban44 Could you try again at https://nextjs.org/conf and enter the same email? Does the button still say "Generate with GitHub"?

**Comment by balazsorban44** [comment]
Going to /conf and entering the email again:
![Screenshot_20200825-220820.png](https://user-images.githubusercontent.com/18369201/91222597-b0891e00-e71f-11ea-9a4c-c73719bd8e09.png)

Clicked register:
![Screenshot_20200825-220847.png](https://user-images.githubusercontent.com/18369201/91222607-b4b53b80-e71f-11ea-8c2c-8c77a6aae7d6.png)

Clicked generate with GitHub
![Screenshot_20200825-220906.png](https://user-images.githubusercontent.com/18369201/91222616-b8e15900-e71f-11ea-82f0-582e4b685faf.png)

**Comment by chibicode** [comment]
@balazsorban44 ok, so it seems like GitHub auth failed 🤔 - it should

![Kapture 2020-08-25 at 13 14 55](https://user-images.githubusercontent.com/992008/91223117-0389b380-e6d5-11ea-8325-0134b84555c4.gif)

**Comment by chibicode** [comment]
@chibicode Great! Thank you for looking into it.

> Update: I ran registering again in incognito mode, than it worked! I use Chrome Canary and Chrome stable on my phone. I started the registering from Canary, but I was redirected to the GitHub consent screen in stable, got redirected back into Canary. I guess this messed things up. In incognito I was able to stay in the same browser under the whole process.
